name: Deploy to GitHub Pages with Firebase Keys

on:
  push:
    branches:
      - main

permissions:
  contents: write  # ✅ Allows pushing to gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Replace Firebase Placeholders in All HTML Files
        run: |
          for file in *.html; do
            sed -i "s|FIRE_BASE_API_KEY|${{ secrets.FIRE_BASE_API_KEY }}|" "$file"
            sed -i "s|MESSAGE_ID|${{ secrets.MESSAGE_ID }}|" "$file"
            sed -i "s|FIREBASE_APP_ID|${{ secrets.FIREBASE_APP_ID }}|" "$file"
            sed -i "s|FIREBASE_MEASUREMENT_ID|${{ secrets.FIREBASE_MEASUREMENT_ID }}|" "$file"
          done

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
